Repository salute-developers/plasma, pull requests merged in 2023-12, with the labels that each got.

#904 plasma-infra: Use 18.16.1 node version
  .nvmrc
Labels: plasma-infra

#892 plasma-infra: Upload assets when publish rc
  .github/workflows/publish-rc.yml
Labels: plasma-infra

#910 plasma-infra: Test upload assets when publish RC
  utils/plasma-tokens-native/package.json
Labels: changelog-skip

#916 chore: update package-lock.json files
  packages/plasma-asdk/package-lock.json
  packages/plasma-b2c/package-lock.json
  packages/plasma-new-hope/package-lock.json
  packages/plasma-web/package-lock.json
Labels: changelog-skip

#908 plasma-infra: Add storybook for "Plasma-ASDK"
  .github/workflows/documentation-main.yml
Labels: plasma-infra

#926 plasma-hope: fix broken style for Upload button
  packages/plasma-hope/src/components/Upload/UploadButton.tsx
Labels: bug, plasma-components

#937 fix(plasma-new-hope): Add support children props to `Tooltip` component
  packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx
  packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts
Labels: plasma-components

#938 plasma-infra: Overrides chokidar version
  package-lock.json
  package.json
Labels: changelog-skip

#946 feat(plasma-new-hope): remove useEffect from typography
  packages/plasma-new-hope/src/components/Typography/Body/Body.tsx
  packages/plasma-new-hope/src/components/Typography/Dspl/Dspl.tsx
  packages/plasma-new-hope/src/components/Typography/Heading/Heading.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Body/Body.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Button/Button.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Caption/Caption.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Display/Display.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Footnote/Footnote.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Headline/Headline.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Paragraph/Paragraph.tsx
  packages/plasma-new-hope/src/components/Typography/Old/ParagraphText/ParagraphText.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Subtitle/Subtitle.tsx
  packages/plasma-new-hope/src/components/Typography/Old/Underline/Underline.tsx
  packages/plasma-new-hope/src/components/Typography/Text/Text.tsx
Labels: plasma-components

#932 Update perftool
  package-lock.json
  package.json
  perftool.config.mts
Labels: plasma-infra

#959 feat(plasma-new-hope): fix CalendarDouble ref
  packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx
Labels: bug

#958 feat(plasma-ui): add property to show/hide subtitle on S viewport
  cypress/snapshots/ui/components/Header/Header.component-test.tsx/plasma-ui Header _size -- _mobile show subtitle.snap.png
  cypress/snapshots/ui/components/Header/NeuHeader.component-test.tsx/plasma-ui NeuHeader _size -- _mobile show subtitle.snap.png
  packages/plasma-ui/src/components/Header/Header.component-test.tsx
  packages/plasma-ui/src/components/Header/Header.stories.tsx
  packages/plasma-ui/src/components/Header/Header.tsx
  packages/plasma-ui/src/components/Header/HeaderSubtitle.tsx
  packages/plasma-ui/src/components/Header/NeuHeader.component-test.tsx
  packages/plasma-ui/src/components/Header/NeuHeader.tsx
Labels: plasma-components
