Repository salute-developers/plasma, pull requests merged in 2024-02, with the labels that each got.

#1027 feat(plasma-tokens): auto generate sdds_srvc theme
  packages/plasma-tokens/data/themes/sdds_srvc.json
  packages/plasma-tokens/src/brands/sdds_srvc/index.ts
  packages/plasma-tokens/src/themes/index.ts
  packages/plasma-tokens/src/themes/sdds_srvc__dark.ts
  packages/plasma-tokens/src/themes/sdds_srvc__light.ts
Labels: changelog-skip

#1022 ci: add sdds-srvc to workflows
  .github/processing-scope.js
  .github/workflows/change-detection.yml
  .github/workflows/documentation-main.yml
  .github/workflows/documentation-pr.yml
  .github/workflows/documentation-pull-request-dev.yml
Labels: changelog-skip

#1029 plasma-infra: Setup s3 DEV stage – manual run
  .github/workflows/documentation-dev-stage-deploy.yml
Labels: plasma-infra

#1037 plasma-infra: Setup dev stage [Part 2]
  .github/workflows/documentation-deploy-stage-dev.yml
  .github/workflows/publish-rc.yml
Labels: plasma-infra, changelog-skip

#1040 fix(plasma-hope): Add value deps for `Select` component with multiselect mode
  packages/plasma-b2c/src/components/Select/Select.stories.tsx
  packages/plasma-hope/src/components/Select/withMultiSelect.tsx
  packages/plasma-web/src/components/Select/Select.stories.tsx
Labels: plasma-components

#1051 chore: add sdds-serv to workflows
  .github/processing-scope.js
  .github/workflows/change-detection.yml
  .github/workflows/documentation-deploy-stage-dev.yml
  .github/workflows/documentation-main.yml
  .github/workflows/documentation-pr.yml
  .github/workflows/documentation-pull-request-dev.yml
Labels: changelog-skip

#1053 chore: bump manual package-locks
  packages/caldera-online/package-lock.json
  packages/caldera/package-lock.json
  packages/plasma-asdk/package-lock.json
  packages/plasma-b2c/package-lock.json
  packages/plasma-core/package-lock.json
  packages/plasma-hope/package-lock.json
  packages/plasma-icons/package-lock.json
  packages/plasma-new-hope/package-lock.json
  packages/plasma-temple/package-lock.json
  packages/plasma-tokens/package-lock.json
  packages/plasma-ui/package-lock.json
  packages/plasma-web/package-lock.json
  packages/sdds-srvc/package-lock.json
  utils/plasma-cy-utils/package-lock.json
  utils/plasma-sb-utils/package-lock.json
Labels: changelog-skip

#1045 chore[sdds-android]: SDDS Android project was created.
  native/sdds-android/.gitignore
  native/sdds-android/LICENCE.txt
  native/sdds-android/README.MD
  native/sdds-android/build.gradle.kts
  native/sdds-android/buildSrc/README.MD
  native/sdds-android/buildSrc/build.gradle.kts
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/Dependencies.kt
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/Plugins.kt
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/SdkConfig.kt
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/Versions.kt
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/conventions/convention.android-app.gradle.kts
  native/sdds-android/buildSrc/src/main/kotlin/buildsrc/conventions/convention.android-lib.gradle.kts
  native/sdds-android/gradle.properties
  native/sdds-android/gradle/wrapper/gradle-wrapper.jar
  native/sdds-android/gradle/wrapper/gradle-wrapper.properties
  native/sdds-android/gradlew
  native/sdds-android/gradlew.bat
  native/sdds-android/plugin_theme_builder/README.MD
  native/sdds-android/plugin_theme_builder/build.gradle.kts
  native/sdds-android/plugin_theme_builder/src/main/kotlin/com/sdds/plugin/themebuilder/ThemeBuilderPlugin.kt
  native/sdds-android/sandbox/README.MD
  native/sdds-android/sandbox/build.gradle.kts
  native/sdds-android/sandbox/src/main/AndroidManifest.xml
  native/sdds-android/sandbox/src/main/res/drawable/ic_launcher_background.xml
  native/sdds-android/sandbox/src/main/res/drawable/ic_launcher_foreground.xml
  native/sdds-android/sandbox/src/main/res/mipmap-anydpi/ic_launcher.xml
  native/sdds-android/sandbox/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  native/sdds-android/sandbox/src/main/res/values/strings.xml
  native/sdds-android/sandbox/src/main/res/values/themes.xml
  native/sdds-android/settings.gradle.kts
  native/sdds-android/uikit-compose/README.MD
  native/sdds-android/uikit-compose/build.gradle.kts
  native/sdds-android/uikit-compose/src/main/AndroidManifest.xml
  native/sdds-android/uikit/README.MD
  native/sdds-android/uikit/build.gradle.kts
  native/sdds-android/uikit/src/main/AndroidManifest.xml
Labels: misc

#1058 plasma-docs: Fix cypress cli commands
  CONTRIBUTING.md
Labels: plasma-docs

#1069 plasma-infra: Fix git error - `9007199254740991: not an integer`
  package-lock.json
  package.json
Labels: plasma-infra, changelog-skip

#1067 feat(plasma-new-hope, web, b2c): Indicator component
  cypress/snapshots/b2c/components/Indicator/Indicator.component-test.tsx/plasma-b2c Indicator -- simple.snap.png
  cypress/snapshots/web/components/Indicator/Indicator.component-test.tsx/plasma-web Indicator -- simple.snap.png
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/src/components/Avatar/Avatar.ts
  packages/plasma-b2c/src/components/Indicator/Indicator.component-test.tsx
  packages/plasma-b2c/src/components/Indicator/Indicator.config.tsx
  packages/plasma-b2c/src/components/Indicator/Indicator.stories.tsx
  packages/plasma-b2c/src/components/Indicator/Indicator.ts
  packages/plasma-b2c/src/components/Indicator/index.ts
  packages/plasma-b2c/src/index.ts
  packages/plasma-new-hope/src/components/Avatar/Avatar.styles.ts
  packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
  packages/plasma-new-hope/src/components/Avatar/utils/getStatusBackgroundColor.ts
  packages/plasma-new-hope/src/components/Avatar/utils/index.tsx
  packages/plasma-new-hope/src/components/Indicator/Indicator.styles.ts
  packages/plasma-new-hope/src/components/Indicator/Indicator.tokens.ts
  packages/plasma-new-hope/src/components/Indicator/Indicator.tsx
  packages/plasma-new-hope/src/components/Indicator/Indicator.types.ts
  packages/plasma-new-hope/src/components/Indicator/index.ts
  packages/plasma-new-hope/src/components/Indicator/variations/_size/base.ts
  packages/plasma-new-hope/src/components/Indicator/variations/_size/tokens.json
  packages/plasma-new-hope/src/components/Indicator/variations/_view/base.ts
  packages/plasma-new-hope/src/components/Indicator/variations/_view/tokens.json
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Avatar/Avatar.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Avatar/Avatar.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Indicator/Indicator.config.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Indicator/Indicator.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Indicator/Indicator.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Indicator/Indicator.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Indicator/Indicator.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Indicator/Indicator.ts
  packages/plasma-new-hope/src/index.ts
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/src/components/Avatar/Avatar.ts
  packages/plasma-web/src/components/Indicator/Indicator.component-test.tsx
  packages/plasma-web/src/components/Indicator/Indicator.config.tsx
  packages/plasma-web/src/components/Indicator/Indicator.stories.tsx
  packages/plasma-web/src/components/Indicator/Indicator.ts
  packages/plasma-web/src/components/Indicator/index.ts
  packages/plasma-web/src/index.ts
  website/plasma-web-docs/docs/components/Avatar.mdx
  website/plasma-web-docs/docs/components/Indicator.mdx
Labels: plasma-components

#1072 fix(sdds-serv): package rename
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/package-lock.json
  packages/sdds-serv/package.json
Labels: changelog-skip

#1075 chore(new-hope): fix overlay stories
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Overlay/Overlay.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Overlay/Overlay.stories.tsx
  packages/plasma-new-hope/src/examples/sds_engineer/components/Overlay/Overlay.stories.tsx
Labels: changelog-skip
