Repository salute-developers/plasma, pull requests merged in 2024-05, with the labels that each got.

#1202 fix(icons): Fix dislike and like
  packages/plasma-icons/src/scalable/Icon.svg.24/DislikeFill.svg
  packages/plasma-icons/src/scalable/Icon.svg.24/LikeFill.svg
Labels: bugs

#1211 Add message for broken perftests
  actions/perftest-helpers/src/modules/writeComment.test.ts
  actions/perftest-helpers/src/modules/writeComment.ts
Labels: changelog-skip

#1209 fix(plasma-*): Fix padding on textarea
  cypress/snapshots/b2c/components/TextArea/TextArea.component-test.tsx/plasma-b2c TextArea -- _size empty.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.component-test.tsx/plasma-b2c TextArea -- _size with content.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.component-test.tsx/plasma-b2c TextArea -- _size.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- contentRight.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- custom width and height.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- default.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- defaultValue.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- disabled.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- empty.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- focused.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- leftHelper and rightHelper.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- placeholder with multiline.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- resize.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- success, warning, error.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - basic.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - manualResize.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - maxAuto.snap.png
  cypress/snapshots/b2c/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - minAuto.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaBase.component-test.tsx/plasma-core TextArea -- empty.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - basic.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - manualResize.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - maxAuto.snap.png
  cypress/snapshots/web/components/TextArea/TextAreaResize.component-test.tsx/plasma-hope TextArea -- autoResize - minAuto.snap.png
  packages/plasma-b2c/src/components/TextArea/TextArea.config.ts
  packages/plasma-b2c/src/components/TextArea/TextArea.stories.tsx
  packages/plasma-new-hope/src/components/TextArea/TextArea.tokens.ts
  packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
  packages/plasma-new-hope/src/components/TextArea/mixins/applyDynamicLabel.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/TextArea/TextArea.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/TextArea/TextArea.config.ts
  packages/plasma-web/src/components/TextArea/TextArea.config.ts
  packages/plasma-web/src/components/TextArea/TextArea.stories.tsx
Labels: plasma-components

#1218 Update perftool
  package-lock.json
  package.json
Labels: changelog-skip

#1217 Fix checkbox types
  packages/caldera-online/api/caldera-online.api.md
  packages/caldera-online/src/components/Checkbox/Checkbox.tsx
  packages/caldera-online/src/components/Radiobox/Radiobox.ts
  packages/plasma-asdk/api/plasma-asdk.api.md
  packages/plasma-asdk/src/components/Checkbox/Checkbox.stories.tsx
  packages/plasma-asdk/src/components/Checkbox/Checkbox.tsx
  packages/plasma-asdk/src/components/Radiobox/Radiobox.stories.tsx
  packages/plasma-asdk/src/components/Radiobox/Radiobox.ts
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/src/components/Checkbox/Checkbox.tsx
  packages/plasma-b2c/src/components/Radiobox/Radiobox.ts
  packages/plasma-new-hope/src/components/Checkbox/Checkbox.types.ts
  packages/plasma-new-hope/src/components/Radiobox/Radiobox.tsx
  packages/plasma-new-hope/src/mixins/applyDisabled.ts
  packages/plasma-new-hope/src/mixins/index.ts
  packages/plasma-new-hope/src/types/InputHTMLAttributes.ts
  packages/plasma-new-hope/src/types/index.ts
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/src/components/Checkbox/Checkbox.tsx
  packages/plasma-web/src/components/Radiobox/Radiobox.ts
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/src/components/Checkbox/Checkbox.tsx
  packages/sdds-serv/src/components/Radiobox/Radiobox.ts
Labels: bugs
