Repository salute-developers/plasma, pull requests merged in 2024-08, with the labels that each got.

#1337 plasma-ui: fix TimePicker perftest
  packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx
Labels: changelog-skip

#1328 RenderTarget in Select
  cypress/snapshots/b2c/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Content -- setSelect.snap.png
  cypress/snapshots/b2c/components/SelectNew/Select.component-test.tsx/plasma-b2c SelectNew -- basic logic.snap.png
  cypress/snapshots/web/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Content -- setSelect.snap.png
  cypress/snapshots/web/components/SelectNew/Select.component-test.tsx/plasma-web SelectNew -- basic logic.snap.png
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-new-hope/src/components/Button/Button.styles.ts
  packages/plasma-new-hope/src/components/Button/Button.tokens.ts
  packages/plasma-new-hope/src/components/Select/Select.styles.ts
  packages/plasma-new-hope/src/components/Select/Select.tokens.ts
  packages/plasma-new-hope/src/components/Select/Select.tsx
  packages/plasma-new-hope/src/components/Select/Select.types.ts
  packages/plasma-new-hope/src/components/Select/hooks/useKeyboardNavigation.ts
  packages/plasma-new-hope/src/components/Select/ui/Target/Target.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/Target.types.ts
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Button/Button.styles.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Button/Button.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Button/Button.types.ts
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.styles.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.types.ts
  packages/plasma-new-hope/src/components/Select/utils/getButtonLabel.ts
  packages/plasma-web/api/plasma-web.api.md
  packages/sdds-cs/api/sdds-cs.api.md
  packages/sdds-dfa/api/sdds-dfa.api.md
  packages/sdds-serv/api/sdds-serv.api.md
  website/plasma-web-docs/docs/components/SelectNew.mdx
  website/sdds-dfa-docs/docs/components/Select.mdx
  website/sdds-serv-docs/docs/components/Select.mdx
Labels: plasma-components

#1339 fix: fix Notification animation overflow
  packages/plasma-new-hope/src/components/Notification/NotificationsPortal.tsx
Labels: bugs

#1340 test(plasma-b2c): update tests and snapshots for Button and Range
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1012] Button stretching=fixed.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1013] Button enableContentLeft, enableContentRight.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1015] Button stretching=auto.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1017] Button pin=square-clear.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1018] Button pin=clear-square.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1019] Button pin=clear-clear.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1020] Button pin=clear-circle.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1021] Button pin=circle-clear.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1022] Button pin=circle-circle.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1023] Button with value.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T1178] Button contentPlacing=relaxed, stretching=filled.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T678] Button view=default, size=m.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T870] Button view=accent, size=l.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T871] Button view=success, size=s.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T872] Button view=warning, size=xs.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T873] Button view=critical, size=xxs.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T876] Button square.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T877] Button stretching=filled.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- [PLASMA-T878] Button disabled.snap.png
  cypress/snapshots/b2c/components/Button/Button.update-test.component-test.tsx/plasma-b2c Button -- withAutoFocus.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1001] Range enableSecondTextfieldContentRight.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1002] Range firstValueError.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1003] Range firstValueSuccess.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1004] Range firstValueSuccess, secondValueSuccess.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1005] Range firstValueError, secondValueError.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1006] Range firstField clicked.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1016] Range secondField clicked.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1192] Range secondValueError.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T1193] Range secondValueSuccess.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T984] Range size=l.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T985] Range disabled.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T986] Range readOnly.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T987] Range enableContentRight, size=m.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T988] Range enableContentLeft, size=s.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T989] Range dividerVariant=none, size=xs.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T990] Range enableFirstTextfieldContentLeft, dividerVariant=none.snap.png
  cypress/snapshots/b2c/components/Range/Range.update-test.component-test.tsx/plasma-b2c Range -- [PLASMA-T991] Range enableFirstTextfieldContentRight, enableSecondTextfieldContentLeft.snap.png
  packages/plasma-b2c/src/components/Button/Button.update-test.component-test.tsx
  packages/plasma-b2c/src/components/Range/Range.update-test.component-test.tsx
Labels: misc

#1367 feat(*-themes): Add brightness tokens to all themes
  packages/themes/caldera-online-themes/src/css/caldera_online.module.css
  packages/themes/caldera-online-themes/src/css/caldera_online__dark.css
  packages/themes/caldera-online-themes/src/css/caldera_online__light.css
  packages/themes/caldera-online-themes/src/themes/caldera_online__dark.ts
  packages/themes/caldera-online-themes/src/themes/caldera_online__light.ts
  packages/themes/caldera-online-themes/src/tokens/caldera_online/index.ts
  packages/themes/caldera-online-themes/src/tokens/index.ts
  packages/themes/flamingo-themes/src/css/flamingo.module.css
  packages/themes/flamingo-themes/src/css/flamingo__dark.css
  packages/themes/flamingo-themes/src/css/flamingo__light.css
  packages/themes/flamingo-themes/src/themes/flamingo__dark.ts
  packages/themes/flamingo-themes/src/themes/flamingo__light.ts
  packages/themes/flamingo-themes/src/tokens/flamingo/index.ts
  packages/themes/flamingo-themes/src/tokens/index.ts
  packages/themes/plasma-themes/src/css/plasma_b2c.module.css
  packages/themes/plasma-themes/src/css/plasma_b2c__dark.css
  packages/themes/plasma-themes/src/css/plasma_b2c__light.css
  packages/themes/plasma-themes/src/css/plasma_web.module.css
  packages/themes/plasma-themes/src/css/plasma_web__dark.css
  packages/themes/plasma-themes/src/css/plasma_web__light.css
  packages/themes/plasma-themes/src/css/stylesSalute.module.css
  packages/themes/plasma-themes/src/css/stylesSalute__dark.css
  packages/themes/plasma-themes/src/css/stylesSalute__light.css
  packages/themes/plasma-themes/src/themes/plasma_b2c__dark.ts
  packages/themes/plasma-themes/src/themes/plasma_b2c__light.ts
  packages/themes/plasma-themes/src/themes/plasma_web__dark.ts
  packages/themes/plasma-themes/src/themes/plasma_web__light.ts
  packages/themes/plasma-themes/src/themes/stylesSalute__dark.ts
  packages/themes/plasma-themes/src/themes/stylesSalute__light.ts
  packages/themes/plasma-themes/src/tokens/index.ts
  packages/themes/plasma-themes/src/tokens/plasma_b2c/index.ts
  packages/themes/plasma-themes/src/tokens/plasma_web/index.ts
  packages/themes/plasma-themes/src/tokens/stylesSalute/index.ts
  packages/themes/sdds-themes/src/css/sdds_cs.module.css
  packages/themes/sdds-themes/src/css/sdds_cs__dark.css
  packages/themes/sdds-themes/src/css/sdds_cs__light.css
  packages/themes/sdds-themes/src/css/sdds_dfa.module.css
  packages/themes/sdds-themes/src/css/sdds_dfa__dark.css
  packages/themes/sdds-themes/src/css/sdds_dfa__light.css
  packages/themes/sdds-themes/src/css/sdds_serv.module.css
  packages/themes/sdds-themes/src/css/sdds_serv__dark.css
  packages/themes/sdds-themes/src/css/sdds_serv__light.css
  packages/themes/sdds-themes/src/themes/sdds_cs__dark.ts
  packages/themes/sdds-themes/src/themes/sdds_cs__light.ts
  packages/themes/sdds-themes/src/themes/sdds_dfa__dark.ts
  packages/themes/sdds-themes/src/themes/sdds_dfa__light.ts
  packages/themes/sdds-themes/src/themes/sdds_serv__dark.ts
  packages/themes/sdds-themes/src/themes/sdds_serv__light.ts
  packages/themes/sdds-themes/src/tokens/index.ts
  packages/themes/sdds-themes/src/tokens/sdds_cs/index.ts
  packages/themes/sdds-themes/src/tokens/sdds_dfa/index.ts
  packages/themes/sdds-themes/src/tokens/sdds_serv/index.ts
Labels: plasma-tokens

#1356 refator(*-docs): Update introducing docs
  scaffold/template-docs/docs/intro.mdx
  website/plasma-web-docs/docs/design/tokens.mdx
  website/plasma-web-docs/docs/intro.mdx
  website/sdds-cs-docs/docs/intro.mdx
  website/sdds-dfa-docs/docs/intro.mdx
  website/sdds-serv-docs/docs/intro.mdx
Labels: plasma-docs

#1359 fix(new-hope): Textfield label bug
  packages/plasma-new-hope/src/components/TextField/variations/_label-placement/base.ts
Labels: plasma-components

#1375 feat(plasma-tokens): auto generate plasma_web theme
  packages/plasma-tokens/data/themes/plasma_web.json
  packages/plasma-tokens/src/brands/plasma_web/index.ts
  packages/plasma-tokens/src/themes/plasma_web__dark.ts
  packages/plasma-tokens/src/themes/plasma_web__light.ts
Labels: changelog-skip

#1325 plasma-*: Fix `Modal` overflow-y side effect
  cypress/snapshots/b2c/components/ModalBase/ModalBase.component-test.tsx/plasma-web ModalBase -- double close.snap.png
  cypress/snapshots/web/components/ModalBase/ModalBase.component-test.tsx/plasma-web ModalBase -- double close.snap.png
  packages/plasma-new-hope/src/components/Modal/Modal.tsx
  packages/plasma-new-hope/src/components/Modal/hooks/useModal.ts
  packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
  packages/plasma-new-hope/src/components/Popup/hooks/usePopup.ts
  packages/plasma-web/src/components/ModalBase/ModalBase.component-test.tsx
Labels: bugs

#1378 plasma-website: fix searchForm input text shifting
  website/plasma-website/components/roster/SearchForm.tsx
Labels: bugs, plasma-docs

#1380 plasma-*: Fix Modal Overlay & Popup registration logic
  packages/plasma-new-hope/src/components/Modal/Modal.tsx
  packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
Labels: plasma-components

#1381 fix(plasma-tokens): Update tokens for plasma themes
  packages/plasma-tokens/data/themes/plasma_b2c.json
  packages/plasma-tokens/data/themes/plasma_web.json
  packages/plasma-tokens/src/brands/plasma_b2c/index.ts
  packages/plasma-tokens/src/brands/plasma_web/index.ts
  packages/plasma-tokens/src/themes/plasma_b2c__dark.ts
  packages/plasma-tokens/src/themes/plasma_b2c__light.ts
  packages/plasma-tokens/src/themes/plasma_web__dark.ts
  packages/plasma-tokens/src/themes/plasma_web__light.ts
Labels: changelog-skip

#1387 chore: Delete unnecessary themes: caldera, flamingo
  .eslintignore
  packages/plasma-tokens/data/themes/caldera_online.json
  packages/plasma-tokens/data/themes/flamingo.json
  packages/plasma-tokens/src/brands/caldera_online/index.ts
  packages/plasma-tokens/src/brands/flamingo/index.ts
  packages/plasma-tokens/src/themes/caldera_online__dark.ts
  packages/plasma-tokens/src/themes/caldera_online__light.ts
  packages/plasma-tokens/src/themes/flamingo__dark.ts
  packages/plasma-tokens/src/themes/flamingo__light.ts
  packages/plasma-tokens/src/themes/index.ts
  packages/themes/caldera-online-themes/.eslintrc.js
  packages/themes/caldera-online-themes/.gitignore
  packages/themes/caldera-online-themes/.npmrc
  packages/themes/caldera-online-themes/CHANGELOG.md
  packages/themes/caldera-online-themes/LICENSE.txt
  packages/themes/caldera-online-themes/README.md
  packages/themes/caldera-online-themes/lib/index.ts
  packages/themes/caldera-online-themes/package-lock.json
  packages/themes/caldera-online-themes/package.json
  packages/themes/caldera-online-themes/src/css/caldera_online.module.css
  packages/themes/caldera-online-themes/src/css/caldera_online__dark.css
  packages/themes/caldera-online-themes/src/css/caldera_online__light.css
  packages/themes/caldera-online-themes/src/index.ts
  packages/themes/caldera-online-themes/src/themes/caldera_online__dark.ts
  packages/themes/caldera-online-themes/src/themes/caldera_online__light.ts
  packages/themes/caldera-online-themes/src/themes/index.ts
  packages/themes/caldera-online-themes/src/tokens/caldera_online/index.ts
  packages/themes/caldera-online-themes/src/tokens/index.ts
  packages/themes/caldera-online-themes/tsconfig.es.json
  packages/themes/caldera-online-themes/tsconfig.json
  packages/themes/flamingo-themes/.eslintrc.js
  packages/themes/flamingo-themes/.gitignore
  packages/themes/flamingo-themes/.npmrc
  packages/themes/flamingo-themes/CHANGELOG.md
  packages/themes/flamingo-themes/LICENSE.txt
  packages/themes/flamingo-themes/README.md
  packages/themes/flamingo-themes/lib/index.ts
  packages/themes/flamingo-themes/package-lock.json
  packages/themes/flamingo-themes/package.json
  packages/themes/flamingo-themes/src/css/flamingo.module.css
  packages/themes/flamingo-themes/src/css/flamingo__dark.css
  packages/themes/flamingo-themes/src/css/flamingo__light.css
  packages/themes/flamingo-themes/src/index.ts
  packages/themes/flamingo-themes/src/themes/flamingo__dark.ts
  packages/themes/flamingo-themes/src/themes/flamingo__light.ts
  packages/themes/flamingo-themes/src/themes/index.ts
  packages/themes/flamingo-themes/src/tokens/flamingo/index.ts
  packages/themes/flamingo-themes/src/tokens/index.ts
  packages/themes/flamingo-themes/tsconfig.es.json
  packages/themes/flamingo-themes/tsconfig.json
  scaffold/Readme.md
Labels: changelog-skip

#1379 feat(plasma-tokens): auto generate sdds_cs theme
  packages/plasma-tokens/data/themes/sdds_cs.json
  packages/plasma-tokens/src/brands/sdds_cs/index.ts
  packages/plasma-tokens/src/themes/sdds_cs__dark.ts
  packages/plasma-tokens/src/themes/sdds_cs__light.ts
Labels: changelog-skip

#1353 test(plasma-b2c): update tests for Breadcrumbs and Price
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1160] Breadcrumbs size=m.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1161] Breadcrumbs size=l.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1162] Breadcrumbs size=s.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1163] Breadcrumbs size=xs.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1165] Breadcrumbs showItems=4.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1168] Breadcrumbs showItems=1.snap.png
  cypress/snapshots/b2c/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx/plasma-b2c Breadcrumbs -- [PLASMA-T1169] Breadcrumbs customShorter.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- [PLASMA-T1124] Price currency=inr, minimumFractionDigits=0.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- [PLASMA-T1138] Price locale=en, minimumFractionDigits=1.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- [PLASMA-T716] Price currency=rub.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- [PLASMA-T717] Price currency=usd, stroked.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- [PLASMA-T718] Price currency=eur, minimumFractionDigits=5.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- handle two prices in a row.snap.png
  cypress/snapshots/b2c/components/Price/Price.update-test.component-test.tsx/plasma-b2c Price -- processing periodicity.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- _currency.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- _minFraction.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- _stroke.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- handle two prices in a row.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- processing periodicity.snap.png
  cypress/snapshots/b2c/components/Price/PriceBase.component-test.tsx/plasma-core Price -- simple.snap.png
  packages/plasma-b2c/src/components/Breadcrumbs/Breadcrumbs.update-test.component-test.tsx
  packages/plasma-b2c/src/components/Price/Price.update-test.component-test.tsx
Labels: misc

#1366 test(plasma-b2c): update tests for Badge and Chip
  cypress/snapshots/b2c/components/Badge/Badge.component-test.tsx/plasma-web Badge -- _view.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T707] Badge view=default, size=m.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T708] Badge view=positive, size=s.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T709] Badge view=negative, with Icon.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T716] Badge view=accent, pilled.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T717] Badge view=warning, size=l.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T718] Badge view=dark.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T719] Badge view=light.snap.png
  cypress/snapshots/b2c/components/Badge/Badge.update-test.component-test.tsx/plasma-web Badge -- [PLASMA-T720] Badge view=default, transparent.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- _pilled.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- _sizes.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- _view transparent.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- _view.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- simple.snap.png
  cypress/snapshots/b2c/components/Badge/BadgeBase.component-test.tsx/plasma-core Badge -- with Icon.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T1194] Chip without Clear.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T757] Chip view=default, size=m.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T758] Chip view=secondary, size=s.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T759] Chip view=accent, size=l.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T761] Chip disabled.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T973] Chip pilled, size=xs.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T974] Chip with Icon.snap.png
  cypress/snapshots/b2c/components/Chip/Chip.update-test.component-test.tsx/plasma-b2c Chip -- [PLASMA-T977] Chip fixed width.snap.png
  packages/plasma-b2c/src/components/Badge/Badge.component-test.tsx
  packages/plasma-b2c/src/components/Badge/Badge.update-test.component-test.tsx
  packages/plasma-b2c/src/components/Badge/BadgeBase.component-test.tsx
  packages/plasma-b2c/src/components/Chip/Chip.update-test.component-test.tsx
Labels: misc

#1395 plasma-web: size `xs` added to `TextField`
  packages/plasma-web/src/components/TextField/TextField.tsx
Labels: plasma-components

#1407 test(plasma-b2c): update tests for ButtonGroup and IconButton
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T1206] ButtonGroup size=s, view=clear.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T1207] ButtonGroup size=xs, gap=dense.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T820] ButtonGroup view=default, size=m, orientation=horizontal.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T821] ButtonGroup view=accent, size=l, shape=default.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T822] ButtonGroup view=secondary, gap=none.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T823] ButtonGroup view=success, orientation=vertical.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T824] ButtonGroup view=warning, shape=segmented.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T825] ButtonGroup view=critical, stretching=filled.snap.png
  cypress/snapshots/b2c/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx/plasma-b2c ButtonGroup -- [PLASMA-T826] ButtonGroup size=xxs, gap=wide.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.component-test.tsx/plasma-web IconButton -- _pin.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.component-test.tsx/plasma-web IconButton -- _size.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.component-test.tsx/plasma-web IconButton -- _view.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.component-test.tsx/plasma-web IconButton -- with Loader.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T925] IconButton view=default, size=m.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T926] IconButton view=accent, size=l.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T927] IconButton view=secondary, size=s.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T928] IconButton view=success, size=xs.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T929] IconButton view=warning, isLoading.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T930] IconButton disabled.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T931] IconButton view=critical, pin=square-clear.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T932] IconButton view=clear, pin=clear-square.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T933] IconButton pin=clear-clear.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T934] IconButton pin=clear-circle.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T935] IconButton pin=circle-clear.snap.png
  cypress/snapshots/b2c/components/IconButton/IconButton.update-test.component-test.tsx/plasma-b2c IconButton -- [PLASMA-T936] IconButton pin=circle-circle.snap.png
  packages/plasma-b2c/src/components/ButtonGroup/ButtonGroup.update-test.component-test.tsx
  packages/plasma-b2c/src/components/IconButton/IconButton.component-test.tsx
  packages/plasma-b2c/src/components/IconButton/IconButton.update-test.component-test.tsx
Labels: misc

#1410 plasma-*: PopupProvider server rendering [HOTFIX]
  packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
Labels: Hotfix, changelog-skip
