Repository salute-developers/plasma, pull requests merged in 2024-09, with the labels that each got.

#1404 plasma-(*): Add format and lang in Datepicker
  packages/plasma-b2c/src/components/DatePicker/DatePicker.stories.tsx
  packages/plasma-new-hope/src/components/DatePicker/DatePicker.template-doc.mdx
  packages/plasma-new-hope/src/components/DatePicker/DatePickerBase.types.ts
  packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
  packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
  packages/plasma-new-hope/src/components/DatePicker/hooks/useDatePicker.ts
  packages/plasma-new-hope/src/components/DatePicker/utils/dateHelper.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/DatePicker/DatePicker.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/DatePicker/DatePicker.stories.tsx
  packages/plasma-new-hope/src/utils/datejs.ts
  packages/plasma-web/src/components/DatePicker/DatePicker.stories.tsx
  packages/sdds-cs/src/components/DatePicker/DatePicker.stories.tsx
  packages/sdds-dfa/src/components/DatePicker/DatePicker.stories.tsx
  packages/sdds-serv/src/components/DatePicker/DatePicker.stories.tsx
  website/plasma-b2c-docs/docs/components/DatePicker.mdx
  website/plasma-web-docs/docs/components/DatePicker.mdx
  website/sdds-cs-docs/docs/components/DatePicker.mdx
  website/sdds-dfa-docs/docs/components/DatePicker.mdx
  website/sdds-serv-docs/docs/components/DatePicker.mdx
Labels: plasma-components

#1411 plasma-*: PopupProvider server rendering
  packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
Labels: Hotfix, changelog-skip

#1364 plasma-{web,b2c}: update ModalBase modalOverlayColor token
  cypress/snapshots/web/components/ModalBase/ModalBase.component-test.tsx/plasma-web ModalBase -- double close.snap.png
  cypress/snapshots/web/components/ModalBase/ModalBase.component-test.tsx/plasma-web ModalBase -- simple.snap.png
  packages/plasma-b2c/src/components/ModalBase/Modal.config.ts
  packages/plasma-web/src/components/ModalBase/Modal.config.ts
Labels: plasma-components

#1425 plasma-*: Fix `TextField` placeholder logic [HOTFIX]
  cypress/snapshots/b2c/components/TextField/TextField.component-test.tsx/plasma-web TextField -- _defaultValue.snap.png
  cypress/snapshots/web/components/TextField/TextField.component-test.tsx/plasma-web TextField -- _defaultValue.snap.png
  packages/plasma-b2c/src/components/TextField/TextField.component-test.tsx
  packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
  packages/plasma-new-hope/src/components/TextField/TextField.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/TextField/TextField.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/TextField/TextField.stories.tsx
  packages/plasma-web/src/components/TextField/TextField.component-test.tsx
  packages/plasma-web/src/components/TextField/TextField.stories.tsx
  packages/sdds-cs/src/components/TextField/TextField.stories.tsx
  packages/sdds-dfa/src/components/TextField/TextField.stories.tsx
  packages/sdds-finportal/src/components/TextField/TextField.stories.tsx
  packages/sdds-serv/src/components/TextField/TextField.stories.tsx
Labels: Hotfix, changelog-skip

#1423 test(plasma-b2c): update tests for Slider and Tabs
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T697] Slider view=default, size=m, labelPlacement=outer.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T937] Slider disabled.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T938] Slider view=accent, size=l, rangeValuesPlacement=outer.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T939] Slider view=gradient, size=s.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T940] Slider min=10, labelPlacement=inner.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T941] Slider max=123, rangeValuesPlacement=inner.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T942] Slider showCurrentValue.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T943] Slider disableShowRangeValues.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T947] Slider focused.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T699] Tabs size=xs, view=divider.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T799] Tabs disabled.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T800] Tabs size=s, enableContentLeft, enableContentRight.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T801] Tabs size=m, stretch.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T802] Tabs size=l, without divider.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T803] Tabs clicking on arrows scrolls to previous or next.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T818] Tabs clip=scroll.snap.png
  cypress/snapshots/b2c/components/Tabs/Tabs.update-test.component-test.tsx/plasma-b2c Tabs -- [PLASMA-T819] Tabs size=h3.snap.png
  packages/plasma-b2c/src/components/Slider/Slider.update-test.component-test.tsx
  packages/plasma-b2c/src/components/Tabs/Tabs.update-test.component-test.tsx
Labels: misc

#1394 test(plasma-b2c): update tests for DatePicker and Card
  cypress/snapshots/b2c/components/Card/Card.update-test.component-test.tsx/plasma-b2c Card -- [PLASMA-T1203] Card with background.snap.png
  cypress/snapshots/b2c/components/Card/Card.update-test.component-test.tsx/plasma-b2c Card -- [PLASMA-T1204] Card with cover, enableCoverGradient.snap.png
  cypress/snapshots/b2c/components/Card/Card.update-test.component-test.tsx/plasma-b2c Card -- [PLASMA-T1205] Card with cover.snap.png
  cypress/snapshots/b2c/components/Card/Card.update-test.component-test.tsx/plasma-b2c Card -- [PLASMA-T710] Card default.snap.png
  cypress/snapshots/b2c/components/Card/Card.update-test.component-test.tsx/plasma-b2c Card -- [PLASMA-T711] Card roundness=0.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1097] DatePicker size=l.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1098] DatePicker disabled.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1099] DatePicker readOnly.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1101] DatePicker valueError, enableContentRight.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1102] DatePicker valueSuccess, enableContentLeft.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1103] DatePicker size=m.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1104] DatePicker size=s.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1105] DatePicker size=xs.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1106] DatePicker select month by arrows.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1107] DatePicker select month in popover.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1108] DatePicker select year by arrows.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1110] DatePicker select year in popover.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1111] DatePicker select day in popover.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1112] DatePicker input date.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1114] DatePicker label, leftHelper, placeholder.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1200] DatePicker inner label without input value.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1201] DatePicker inner label with input value.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- default.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- prop format.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- prop input masked date.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- prop onToggle, outside click.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- prop placement.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- [PLASMA-T1115] DatePickerRange default.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- [PLASMA-T1116] DatePickerRange input date.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- [PLASMA-T1117] DatePickerRange input same date.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- [PLASMA-T1119] DatePickerRange default, double calendar.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- [PLASMA-T1120] DatePickerRange input date, double calendar.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop defaultDate, enableContent.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop disabled, readOnly.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop format.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop label, leftHelper, placeholder.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop placement.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop size l.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop size m.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop size s.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop size xs.snap.png
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePickerRange -- prop valueError, valueSuccess.snap.png
  packages/plasma-b2c/src/components/Card/Card.component-test.tsx
  packages/plasma-b2c/src/components/Card/Card.update-test.component-test.tsx
  packages/plasma-b2c/src/components/DatePicker/DatePicker.update-test.component-test.tsx
Labels: misc

#1431 fix(sdds-*): Use correct default view for Grid
  packages/plasma-new-hope/src/components/Grid/Grid.tsx
  packages/sdds-cs/src/components/Grid/Grid.config.tsx
  packages/sdds-dfa/src/components/Grid/Grid.config.tsx
  packages/sdds-finportal/src/components/Grid/Grid.config.tsx
  packages/sdds-serv/src/components/Grid/Grid.config.tsx
Labels: plasma-components

#1433 feat(plasma-new-hope): Add TextField ref to deps for placeholder
  packages/plasma-new-hope/src/components/TextField/TextField.tsx
Labels: changelog-skip

#1436 plasma-*: Fixed issue with predefined value in single Combobox
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
Labels: plasma-components

#1434 test(plasma-b2c): update tests for TextArea
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1041] TextArea autoResize, minAuto.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1234] TextArea autoResize, maxAuto.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1235] TextArea custom height and width.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1236] TextArea resize=horizontal.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1237] TextArea resize=vertical.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1238] TextArea resize=both.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1239] TextArea labelPlacement=inner, requiredPlacement=left.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1240] TextArea labelPlacement=inner, requiredPlacement=right.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1241] TextArea labelPlacement=outer, requiredPlacement=left.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T1242] TextArea labelPlacement=outer, requiredPlacement=right.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T700] TextArea size=m, with content.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T742] TextArea with value, without content.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T743] TextArea disabled.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T744] TextArea readOnly.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T745] TextArea status=success, size=s.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T746] TextArea status=warning, size=l.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T747] TextArea status=error, size=xs.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T766] TextArea focused.snap.png
  cypress/snapshots/b2c/components/TextArea/TextArea.update-test.component-test.tsx/plasma-b2c TextArea -- [PLASMA-T768] TextArea autoResize.snap.png
  packages/plasma-b2c/src/components/TextArea/TextArea.update-test.component-test.tsx
Labels: misc

#1455 feat(plasma-web, b2c): Added mappings for placement prop in Dropdown
  packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
  packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
  packages/sdds-cs/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-dfa/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-finportal/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-serv/src/components/Combobox/Combobox.stories.tsx
Labels: plasma-components

#1447 plasma-*: Fix Switch Config
  packages/plasma-asdk/api/plasma-asdk.api.md
  packages/plasma-asdk/src/components/Switch/Switch.config.ts
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/scripts/copy-linaria-components.sh
  packages/plasma-b2c/src/components/Switch/Switch.config.ts
  packages/plasma-new-hope/src/components/Switch/Switch.styles.ts
  packages/plasma-new-hope/src/components/Switch/Switch.tokens.ts
  packages/plasma-new-hope/src/components/Switch/Switch.tsx
  packages/plasma-new-hope/src/components/Switch/_label-position/after.ts
  packages/plasma-new-hope/src/components/Switch/_label-position/base.ts
  packages/plasma-new-hope/src/components/Switch/_label-position/before.ts
  packages/plasma-new-hope/src/components/Switch/_label-position/tokens.json
  packages/plasma-new-hope/src/components/Switch/_size/base.ts
  packages/plasma-new-hope/src/components/Switch/index.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.config.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.config.ts
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/scripts/copy-linaria-components.sh
  packages/plasma-web/src/components/Switch/Switch.config.ts
  packages/sdds-cs/api/sdds-cs.api.md
  packages/sdds-cs/src/components/Switch/Switch.config.ts
  packages/sdds-dfa/api/sdds-dfa.api.md
  packages/sdds-dfa/src/components/Switch/Switch.config.ts
  packages/sdds-finportal/api/sdds-finportal.api.md
  packages/sdds-finportal/src/components/Switch/Switch.config.ts
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/src/components/Switch/Switch.config.ts
Labels: plasma-components

#1453 test(plasma-b2c): update tests for Mask
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1243] Mask view=default, size=l, alwaysShowMask, empty.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1244] Mask view=positive, size=m, optional.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1245] Mask view=warning, size=s, requiredPlacement=right.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1246] Mask view=negative, size=xs, requiredPlacement=left.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1247] Mask disabled.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1248] Mask readOnly.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1281] Mask type letters in telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1282] Mask type number 7 in telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1283] Mask type not number 7 in telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1284] Mask delete number in telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1285] Mask type in fully filled telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1286] Mask paste in empty telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1287] Mask paste in partially filled telephone.snap.png
  cypress/snapshots/b2c/components/Mask/Mask.update-test.component-test.tsx/plasma-b2c Mask -- [PLASMA-T1288] Mask paste in fully filled telephone.snap.png
  packages/plasma-b2c/src/components/Mask/Mask.update-test.component-test.tsx
Labels: misc
