Repository salute-developers/plasma, pull requests merged in 2024-03, with the labels that each got.

#1078 feat(plasma-tokens-*): Add re-export fallback tokens
  packages/plasma-tokens-b2b/generate.ts
  packages/plasma-tokens-b2c/generate.ts
  packages/plasma-tokens-web/generate.ts
Labels: plasma-tokens

#1071 plasma-infra: Update version for "@auto-it" patches
  patches/@auto-it+core+11.1.1.patch
  patches/@auto-it+npm+11.1.1.patch
  patches/@auto-it+upload-assets+11.1.1.patch
Labels: plasma-infra, skip-release, changelog-skip

#1077 plasma-infra: Deploy documentation and storybook artefact to `plasma.sberdevices.ru/dev/`
  .github/workflows/documentation-deploy-dev-subdir.yml
Labels: plasma-infra, skip-release, changelog-skip

#1083 fix(new-hope): remove wrapper from popover
  packages/plasma-new-hope/src/components/Popover/Popover.styles.ts
  packages/plasma-new-hope/src/components/Popover/Popover.tsx
  packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx
Labels: bugs

#1094 fix(plasma-tokens-*): Add `new` directory for for new tokens
  packages/plasma-tokens-b2b/.gitignore
  packages/plasma-tokens-b2b/generate.ts
  packages/plasma-tokens-b2b/package.json
  packages/plasma-tokens-b2c/.gitignore
  packages/plasma-tokens-b2c/generate.ts
  packages/plasma-tokens-b2c/package.json
  packages/plasma-tokens-web/.gitignore
  packages/plasma-tokens-web/generate.ts
  packages/plasma-tokens-web/package.json
Labels: Hotfix, changelog-skip

#1097 chore(sdds-serv-docs): Update versions
  website/sdds-serv-docs/package-lock.json
  website/sdds-serv-docs/package.json
Labels: changelog-skip

#1084 feat(new-hope): edit calendar range logic and fix name
  packages/plasma-new-hope/src/components/Calendar/hooks/useDays.ts
  packages/plasma-new-hope/src/components/Calendar/utils/index.ts
Labels: plasma-components

#1096 plasma-infra: Fix boolean true args in URL getting ignored [Storybook]
  packages/caldera-online/package-lock.json
  packages/caldera-online/package.json
  packages/caldera/package-lock.json
  packages/caldera/package.json
  packages/plasma-asdk/package-lock.json
  packages/plasma-asdk/package.json
  packages/plasma-b2c/package-lock.json
  packages/plasma-b2c/package.json
  packages/plasma-new-hope/package-lock.json
  packages/plasma-new-hope/package.json
  packages/plasma-ui/package-lock.json
  packages/plasma-ui/package.json
  packages/plasma-web/package-lock.json
  packages/plasma-web/package.json
  packages/sdds-serv/package-lock.json
  packages/sdds-serv/package.json
Labels: plasma-infra, changelog-skip

#1089 fix(ui): fix pickers documentation bug with overflow
  packages/plasma-ui/src/components/Pickers/PickerItem.tsx
Labels: bugs

#1082 feat(plasma-new-hope): TextField issue with opacity
  packages/plasma-new-hope/src/components/TextField/TextField.tsx
Labels: plasma-components

#1110 feat: remove scale tokens from Button & ButtonGroup
  packages/caldera-online/src/components/Button/Button.config.ts
  packages/caldera/src/components/Button/Button.config.ts
  packages/plasma-b2c/src/components/Button/Button.config.ts
  packages/plasma-b2c/src/components/ButtonGroup/ButtonGroup.config.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.config.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/ButtonGroup/ButtonGroup.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Button/Button.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/ButtonGroup/ButtonGroup.config.ts
  packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
  packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
  packages/plasma-web/src/components/Button/Button.config.ts
  packages/plasma-web/src/components/ButtonGroup/ButtonGroup.config.ts
  packages/sdds-serv/src/components/Button/Button.config.ts
  packages/sdds-serv/src/components/ButtonGroup/ButtonGroup.config.ts
Labels: plasma-components

#1111 chore: bump manual package-locks
  packages/caldera-online/package-lock.json
  packages/caldera/package-lock.json
  packages/plasma-asdk/package-lock.json
  packages/plasma-b2c/package-lock.json
  packages/plasma-new-hope/package-lock.json
  packages/plasma-web/package-lock.json
  packages/sdds-serv/package-lock.json
Labels: changelog-skip

#1080 feat(plasma-new-hope, b2c): ButtonBase
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/src/components/ButtonBase/index.ts
  packages/plasma-b2c/src/index.ts
  packages/plasma-new-hope/src/components/ButtonBase/index.ts
  packages/plasma-new-hope/src/index.ts
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/src/components/ButtonBase/index.ts
  packages/plasma-web/src/index.ts
Labels: plasma-components

#1109 plasma-icons: script to generate android icons
  packages/plasma-icons/.gitignore
  packages/plasma-icons/README.md
  packages/plasma-icons/archives/android-icons.zip
  packages/plasma-icons/package-lock.json
  packages/plasma-icons/package.json
  packages/plasma-icons/scripts/generateAndroidArchive.ts
Labels: plasma-icons

#1117 plasma-infra: Delete flag `--no-private` [Unit test]
  .github/workflows/required-primary-checks.yml
Labels: plasma-infra, changelog-skip

#1118 plasma-infra(docs-ui): Sync deps version
  utils/plasma-docs-ui/package-lock.json
  utils/plasma-docs-ui/package.json
Labels: plasma-infra, changelog-skip

#1120 plasma-infra(ui-docs): Clean deps
  website/plasma-ui-docs/package-lock.json
  website/plasma-ui-docs/package.json
Labels: plasma-infra, changelog-skip

#1116 fix: change height for Drawer stories
  packages/plasma-b2c/src/components/Drawer/Drawer.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Drawer/Drawer.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Drawer/Drawer.stories.tsx
  packages/plasma-new-hope/src/examples/sds_engineer/components/Drawer/Drawer.stories.tsx
  packages/plasma-web/src/components/Drawer/Drawer.stories.tsx
  packages/sdds-serv/src/components/Drawer/Drawer.stories.tsx
Labels: bugs

#1143 plasma-infra: Fix publish rc
  .github/workflows/publish-rc.yml
Labels: plasma-infra, changelog-skip

#1139 fix(plasma-web,plasma-b2c,plasma-asdk): Replace tokens for background in storybook to new
  packages/plasma-asdk/.storybook/decoratorThemes.tsx
  packages/plasma-asdk/.storybook/preview-head.html
  packages/plasma-b2c/.storybook/decoratorThemes.tsx
  packages/plasma-b2c/.storybook/preview-head.html
  packages/plasma-web/.storybook/decoratorThemes.tsx
  packages/plasma-web/.storybook/preview-head.html
Labels: plasma-docs

#1144 fix(plasma-web,plasma-b2c,plasma-asdk): Remove js token from import with nested directory
  packages/plasma-asdk/.storybook/decoratorThemes.tsx
  packages/plasma-b2c/.storybook/decoratorThemes.tsx
  packages/plasma-web/.storybook/decoratorThemes.tsx
Labels: changelog-skip

#1146 plasma-infra: Refactoring retry for sync package-lock files
  .github/actions/update-package-lock/action.yml
Labels: plasma-infra, changelog-skip

#1145 plasma-infra: Dispatch build-icons event
  .github/workflows/dispatch-custom-event.yml
Labels: plasma-infra

#1149 plasma-icons: Add `old` dir for publish
  packages/plasma-icons/package.json
Labels: plasma-icons

#1104 feat(plasma-new-hope, b2c, web): Dropdown interlayer
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- auto placement bottom.snap.png
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- auto placement top.snap.png
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- block and popup's width.snap.png
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- handling dropdown menu height.snap.png
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- radius and padding.snap.png
  cypress/snapshots/b2c/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- simple.snap.png
  cypress/snapshots/b2c/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Styled -- type.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- auto placement bottom.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- auto placement top.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- block and popup's width.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- handling dropdown menu height.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- radius and padding.snap.png
  cypress/snapshots/web/components/Dropdown/Dropdown.component-test.tsx/plasma-hope Dropdown -- simple.snap.png
  cypress/snapshots/web/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Styled -- _size.snap.png
  cypress/snapshots/web/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Styled -- type.snap.png
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/src/components/Dropdown/Dropdown.config.ts
  packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
  packages/plasma-b2c/src/components/Dropdown/components/Dropdown.tsx
  packages/plasma-b2c/src/components/Dropdown/components/DropdownItem.tsx
  packages/plasma-b2c/src/components/Dropdown/components/DropdownList.tsx
  packages/plasma-b2c/src/components/Dropdown/components/DropdownPopup.tsx
  packages/plasma-b2c/src/components/Dropdown/components/DropdownUncontrolled.tsx
  packages/plasma-b2c/src/components/Dropdown/index.ts
  packages/plasma-b2c/src/components/Popover/Popover.component-test.tsx
  packages/plasma-b2c/src/components/Popover/Popover.stories.tsx
  packages/plasma-hope/src/components/Dropdown/Dropdown.component-test.tsx
  packages/plasma-new-hope/src/components/Dropdown/Dropdown.tsx
  packages/plasma-new-hope/src/components/Popover/Popover.tsx
  packages/plasma-new-hope/src/components/Popover/Popover.types.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropdown/Normal/Dropdown.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropdown/Tight/Dropdown.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Popover/Popover.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Dropdown/Normal/Dropdown.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Dropdown/Tight/Dropdown.stories.tsx
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/src/components/Dropdown/Dropdown.config.ts
  packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
  packages/plasma-web/src/components/Dropdown/Dropdown.tsx
  packages/plasma-web/src/components/Dropdown/components/Dropdown.tsx
  packages/plasma-web/src/components/Dropdown/components/DropdownItem.tsx
  packages/plasma-web/src/components/Dropdown/components/DropdownList.tsx
  packages/plasma-web/src/components/Dropdown/components/DropdownPopup.tsx
  packages/plasma-web/src/components/Dropdown/components/DropdownUncontrolled.tsx
  packages/plasma-web/src/components/Dropdown/index.ts
  packages/plasma-web/src/components/Popover/Popover.stories.tsx
  website/plasma-web-docs/docs/components/Dropdown.mdx
Labels: plasma-components
