Repository salute-developers/plasma, pull requests merged in 2024-01, with the labels that each got.

#890 plasma-infra: Pass cli options for "@auto-it"
  .github/workflows/publish-canary.yml
  .github/workflows/publish-common.yml
  .github/workflows/publish-rc.yml
Labels: plasma-infra

#966 fix(plasma-new-hope): Fix size for `Spinner` component
  packages/plasma-new-hope/src/components/Spinner/Spinner.tsx
Labels: plasma-components

#987 plasma-infra: Fix broken build docs
  packages/plasma-ui/CHANGELOG.md
  packages/plasma-web/CHANGELOG.md
Labels: changelog-skip

#985 feat(plasma-ui): fix Badge tests
  packages/plasma-ui/package.json
  packages/plasma-ui/src/components/Badge/BadgeBase.component-test.tsx
  packages/plasma-ui/src/components/Slider/Slider.component-test.tsx
Labels: changelog-skip

#989 fix(plasma-icons): fix package publish
  packages/plasma-icons/package.json
Labels: plasma-icons

#994 ci: add caldera-package to workflows
  .github/processing-scope.js
  .github/workflows/change-detection.yml
  .github/workflows/documentation-main.yml
  .github/workflows/documentation-pr.yml
Labels: changelog-skip

#996 plasma-infra(documentation): Add documentation workflow for dev branch
  .github/workflows/documentation-pull-request-dev.yml
Labels: plasma-infra

#991 ci: use perftool collaborative mode
  .github/workflows/performance-test-pr.yml
  package-lock.json
  package.json
  perftool.config.mts
Labels: plasma-infra

#995 plasma-infra: Override `lerna ls` config
  lerna.json
Labels: plasma-infra

#962 feat(plasma-new-hope): Avatar & AvatarGroup
  packages/plasma-new-hope/src/components/Avatar/Avatar.styles.ts
  packages/plasma-new-hope/src/components/Avatar/Avatar.tokens.ts
  packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
  packages/plasma-new-hope/src/components/Avatar/Avatar.types.ts
  packages/plasma-new-hope/src/components/Avatar/index.ts
  packages/plasma-new-hope/src/components/Avatar/utils/getInitialsForName.ts
  packages/plasma-new-hope/src/components/Avatar/utils/getStatusBackgroundColor.ts
  packages/plasma-new-hope/src/components/Avatar/utils/index.tsx
  packages/plasma-new-hope/src/components/Avatar/variations/_focused/base.ts
  packages/plasma-new-hope/src/components/Avatar/variations/_focused/tokens.json
  packages/plasma-new-hope/src/components/Avatar/variations/_size/base.ts
  packages/plasma-new-hope/src/components/Avatar/variations/_size/tokens.json
  packages/plasma-new-hope/src/components/AvatarGroup/AvatarGroup.styles.ts
  packages/plasma-new-hope/src/components/AvatarGroup/AvatarGroup.tsx
  packages/plasma-new-hope/src/components/AvatarGroup/AvatarGroup.types.ts
  packages/plasma-new-hope/src/components/AvatarGroup/index.ts
  packages/plasma-new-hope/src/components/_Icon/Icon.assets/Silhouette.tsx
  packages/plasma-new-hope/src/components/_Icon/IconRoot.tsx
  packages/plasma-new-hope/src/engines/linaria.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Avatar/Avatar.config.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Avatar/Avatar.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Avatar/Avatar.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/AvatarGroup/AvatarGroup.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/AvatarGroup/AvatarGroup.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Avatar/Avatar.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/AvatarGroup/AvatarGroup.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/AvatarGroup/AvatarGroup.ts
  packages/plasma-new-hope/src/examples/sds_engineer/components/Avatar/Avatar.config.ts
  packages/plasma-new-hope/src/examples/sds_engineer/components/Avatar/Avatar.stories.tsx
  packages/plasma-new-hope/src/examples/sds_engineer/components/Avatar/Avatar.tsx
  packages/plasma-new-hope/src/examples/sds_engineer/components/AvatarGroup/AvatarGroup.stories.tsx
  packages/plasma-new-hope/src/examples/sds_engineer/components/AvatarGroup/AvatarGroup.ts
  packages/plasma-new-hope/src/index.ts
Labels: plasma-components

#935 plasma-infra: Add notification when publish failed
  .github/workflows/publish-rc.yml
Labels: plasma-infra

#1007 plasma-infra: Refactoring release pull request workflow
  .github/workflows/create-release-pr.yml
Labels: plasma-infra

#1003 ci: add Caldera-online-package to workflows
  .github/processing-scope.js
  .github/workflows/change-detection.yml
  .github/workflows/documentation-main.yml
  .github/workflows/documentation-pr.yml
  .github/workflows/documentation-pull-request-dev.yml
Labels: changelog-skip

#1018 plasma-infra: Delete unnecessary `on:pull_request` into master
  .github/workflows/documentation-pr.yml
Labels: plasma-infra, changelog-skip
