Repository salute-developers/plasma, pull requests merged in 2024-10, with the labels that each got.

#1463 test(plasma-b2c): update tests for Attach
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1296] Attach flow=horizontal.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1297] Attach remove attached file.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1298] Attach flow=vertical.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1299] Attach hasAttachment=false.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1301] flow=auto, filenameTruncation.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1304] Attach view=accent, size=m.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1305] Attach view=default, size=l.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1306] Attach view=secondary, size=s.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1307] Attach view=clear, size=xs.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1308] Attach view=success, square.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1309] Attach view=warning, enableContentLeft.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1310] Attach view=critical, enableContentRight.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1311] Attach view=dark, with buttonValue.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1312] Attach view=black.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1313] Attach view=white.snap.png
  cypress/snapshots/b2c/components/Attach/Attach.update-test.component-test.tsx/plasma-b2c Attach -- [PLASMA-T1315] Attach view=accent, size=m, buttonType=iconButton.snap.png
  packages/plasma-b2c/src/components/Attach/Attach.update-test.component-test.tsx
Labels: misc

#1468 feat(plasma-new-hope): Got rid of styled-components imports in new-hope
  packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
  packages/plasma-new-hope/src/components/Breadcrumbs/ui/BreadcrumbShorter/BreadcrumbShorter.styles.ts
  packages/plasma-new-hope/src/components/ButtonBase/index.ts
  packages/plasma-new-hope/src/components/Cell/Cell.styles.ts
  packages/plasma-new-hope/src/components/Cell/ui/CellTextbox/CellTextbox.styles.ts
  packages/plasma-new-hope/src/components/Cell/ui/CellTextboxLabel/CellTextboxLabel.styles.ts
  packages/plasma-new-hope/src/components/Cell/ui/CellTextboxSubtitle/CellTextboxSubtitle.styles.ts
  packages/plasma-new-hope/src/components/Cell/ui/CellTextboxTitle/CellTextboxTitle.styles.ts
  packages/plasma-new-hope/src/components/Drawer/Drawer.styles.ts
Labels: changelog-skip

#1483 chore: Fix ubuntu version
  .github/workflows/clean-pr-documentation.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/documentation-deploy-pr.yml
  .github/workflows/documentation-deploy-prod.yml
  .github/workflows/documentation-deploy-release-branch.yml
  .github/workflows/documentation-deploy-stage-dev.yml
  .github/workflows/publish-rc.yml
  .github/workflows/theme-builder-deploy-demo.yml
  .github/workflows/theme-builder-pr.yml
  .github/workflows/theme-builder.yml
  .github/workflows/versionate-docs.yml
Labels: changelog-skip

#1444 plasma-*: Focus TextArea by click inside
  packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
Labels: plasma-components

#1346 plasma-infra: improve dsplName for storybook
  packages/plasma-new-hope/.storybook/main.ts
Labels: plasma-infra, changelog-skip

#1419 feat(sdds-serv): Add linaria
  packages/plasma-new-hope/src/components/Accordion/Accordion.types.ts
  packages/sdds-serv/.gitignore
  packages/sdds-serv/.storybook/main.ts
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/package.json
  packages/sdds-serv/rollup.config.mjs
  packages/sdds-serv/scripts/copy-linaria-components.sh
  packages/sdds-serv/src/index.ts
  packages/sdds-serv/styled-components/package.json
  website/sdds-serv-docs/src/theme/ReactLiveScope/index.tsx
Labels: plasma-components

#1484 feat(*): Fix Accordion Right Content and Paddings
  packages/plasma-b2c/src/components/Accordion/Accordion.stories.tsx
  packages/plasma-new-hope/src/components/Accordion/Accordion.template-doc.mdx
  packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
  packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.types.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Accordion/Accordion.stories.tsx
  packages/plasma-web/src/components/Accordion/Accordion.stories.tsx
  packages/sdds-cs/src/components/Accordion/Accordion.config.ts
  packages/sdds-cs/src/components/Accordion/Accordion.stories.tsx
  packages/sdds-dfa/src/components/Accordion/Accordion.config.ts
  packages/sdds-dfa/src/components/Accordion/Accordion.stories.tsx
  packages/sdds-finportal/src/components/Accordion/Accordion.config.ts
  packages/sdds-finportal/src/components/Accordion/Accordion.stories.tsx
  packages/sdds-serv/src/components/Accordion/Accordion.config.ts
  packages/sdds-serv/src/components/Accordion/Accordion.stories.tsx
  website/plasma-b2c-docs/docs/components/Accordion.mdx
  website/plasma-web-docs/docs/components/Accordion.mdx
  website/sdds-cs-docs/docs/components/Accordion.mdx
  website/sdds-dfa-docs/docs/components/Accordion.mdx
  website/sdds-serv-docs/docs/components/Accordion.mdx
Labels: plasma-components

#1499 plasma-infra: Add `plasma-themes` and `core-themes` to workflows
  .github/meta.js
  .github/workflows/ci-unit-tests.yml
  .github/workflows/cypress-common.yml
  .github/workflows/documentation-deploy-pr.yml
  .github/workflows/performance-test-base.yml
  .github/workflows/performance-test-pr.yml
Labels: changelog-skip

#1501 fix(plasma-new-hope): Fix DatePicker placeholder type
  packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.types.ts
Labels: changelog-skip

#1507 fix(sdds-themes): Update typography tokens for `sdds-cs` theme
  packages/themes/sdds-themes/src/css/sdds_cs.module.css
  packages/themes/sdds-themes/src/css/sdds_cs__dark.css
  packages/themes/sdds-themes/src/css/sdds_cs__light.css
  packages/themes/sdds-themes/src/themes/sdds_cs__dark.ts
  packages/themes/sdds-themes/src/themes/sdds_cs__light.ts
Labels: plasma-tokens

#1508 fix(plasma-new-hope): Fix useFocusTrap import
  packages/plasma-new-hope/src/components/Drawer/Drawer.tsx
Labels: changelog-skip

#1504 plasma-*: Update config for `Select`
  packages/plasma-b2c/src/components/Select/Select.config.ts
  packages/plasma-new-hope/src/components/Select/Select.styles.ts
  packages/plasma-new-hope/src/components/Select/Select.tokens.ts
  packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.styles.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Select/Select.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Select/Select.config.ts
  packages/plasma-web/src/components/Select/Select.config.ts
  packages/sdds-cs/src/components/Select/Select.config.ts
  packages/sdds-dfa/src/components/Select/Select.config.ts
  packages/sdds-finportal/src/components/Select/Select.config.ts
  packages/sdds-serv/src/components/Select/Select.config.ts
Labels: plasma-components

#1505 feat(plasma-*, sdds-*): Combobox & Select improvements
  packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/getInitialValue.ts
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/index.ts
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/initialItemsTransform.ts
  packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
  packages/plasma-new-hope/src/components/Select/Select.tsx
  packages/plasma-new-hope/src/components/Select/Select.types.ts
  packages/plasma-new-hope/src/components/Select/hooks/useKeyboardNavigation.ts
  packages/plasma-new-hope/src/components/Select/ui/Target/Target.types.ts
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.styles.tsx
  packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx
  packages/plasma-new-hope/src/components/Select/utils/getButtonLabel.ts
  packages/plasma-new-hope/src/components/Select/utils/getInitialValue.ts
  packages/plasma-new-hope/src/components/Select/utils/index.ts
  packages/plasma-new-hope/src/components/Select/utils/initialItemsTransform.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Combobox/Combobox.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Combobox/Combobox.stories.tsx
  packages/plasma-web/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-cs/api/sdds-cs.api.md
  packages/sdds-cs/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-dfa/api/sdds-dfa.api.md
  packages/sdds-dfa/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-finportal/api/sdds-finportal.api.md
  packages/sdds-finportal/src/components/Combobox/Combobox.stories.tsx
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/src/components/Combobox/Combobox.stories.tsx
  website/plasma-b2c-docs/docs/components/Select.mdx
  website/plasma-web-docs/docs/components/Select.mdx
  website/sdds-cs-docs/docs/components/Select.mdx
  website/sdds-dfa-docs/docs/components/Select.mdx
  website/sdds-serv-docs/docs/components/Select.mdx
Labels: plasma-components

#1503 feat: Notification placement prop
  cypress/snapshots/b2c/components/Notification/Notification.component-test.tsx/plasma-web Notification -- placement bottom-left.snap.png
  cypress/snapshots/web/components/Notification/Notification.component-test.tsx/plasma-web Notification -- placement bottom-left.snap.png
  packages/plasma-b2c/api/plasma-b2c.api.md
  packages/plasma-b2c/src/components/Notification/Notification.stories.tsx
  packages/plasma-b2c/src/components/Notification/Notification.tsx
  packages/plasma-new-hope/src/components/Notification/Notification.styles.ts
  packages/plasma-new-hope/src/components/Notification/Notification.template-doc.mdx
  packages/plasma-new-hope/src/components/Notification/Notification.tokens.ts
  packages/plasma-new-hope/src/components/Notification/Notification.tsx
  packages/plasma-new-hope/src/components/Notification/Notification.types.ts
  packages/plasma-new-hope/src/components/Notification/NotificationsPortal.tsx
  packages/plasma-new-hope/src/components/Notification/NotificationsProvider.tsx
  packages/plasma-new-hope/src/components/Notification/index.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Notification/Notification.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Notification/Notification.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Notification/Notification.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/Notification/Notification.tsx
  packages/plasma-web/api/plasma-web.api.md
  packages/plasma-web/src/components/Notification/Notification.component-test.tsx
  packages/plasma-web/src/components/Notification/Notification.stories.tsx
  packages/plasma-web/src/components/Notification/Notification.tsx
  packages/sdds-cs/api/sdds-cs.api.md
  packages/sdds-cs/src/components/Notification/Notification.stories.tsx
  packages/sdds-cs/src/components/Notification/Notification.tsx
  packages/sdds-dfa/src/components/Notification/Notification.stories.tsx
  packages/sdds-dfa/src/components/Notification/Notification.tsx
  packages/sdds-finportal/api/sdds-finportal.api.md
  packages/sdds-finportal/src/components/Notification/Notification.stories.tsx
  packages/sdds-finportal/src/components/Notification/Notification.tsx
  packages/sdds-serv/api/sdds-serv.api.md
  packages/sdds-serv/src/components/Notification/Notification.stories.tsx
  packages/sdds-serv/src/components/Notification/Notification.tsx
  packages/themes/sdds-themes/README.md
  website/plasma-b2c-docs/docs/components/Notification.mdx
  website/plasma-web-docs/docs/components/Notification.mdx
  website/sdds-cs-docs/docs/components/Notification.mdx
  website/sdds-dfa-docs/docs/components/Notification.mdx
  website/sdds-serv-docs/docs/components/Notification.mdx
Labels: plasma-components

#1513 feat(plasma-*,sdds-*): Refactor TextField/TextArea storybook hint args
  packages/plasma-b2c/src/components/TextArea/TextArea.stories.tsx
  packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/TextArea/TextArea.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_b2c/components/TextField/TextField.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/TextArea/TextArea.stories.tsx
  packages/plasma-new-hope/src/examples/plasma_web/components/TextField/TextField.stories.tsx
  packages/plasma-web/src/components/TextArea/TextArea.stories.tsx
  packages/plasma-web/src/components/TextField/TextField.stories.tsx
  packages/sdds-cs/src/components/TextArea/TextArea.stories.tsx
  packages/sdds-cs/src/components/TextField/TextField.stories.tsx
  packages/sdds-dfa/src/components/TextArea/TextArea.stories.tsx
  packages/sdds-dfa/src/components/TextField/TextField.stories.tsx
  packages/sdds-finportal/src/components/TextArea/TextArea.stories.tsx
  packages/sdds-finportal/src/components/TextField/TextField.stories.tsx
  packages/sdds-serv/src/components/TextArea/TextArea.stories.tsx
  packages/sdds-serv/src/components/TextField/TextField.stories.tsx
Labels: changelog-skip

#1515 fix(plasma-new-hope): Add more canUseDOM checks to Popup
  packages/plasma-new-hope/src/components/Popup/Popup.tsx
  packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
  packages/plasma-new-hope/src/components/Portal/Portal.tsx
Labels: changelog-skip

#1518 feat(plasma-b2c, plasma-web): Combobox component tests
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common disabled.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common readOnly.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common size l.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common size m.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common size s.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- common size xs.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- flow async items loading.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop isTargetAmount.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop listWidth, listHeight, listOverflow.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop placement.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop renderItem.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop renderValue.snap.png
  cypress/snapshots/b2c/components/Combobox/Combobox.component-test.tsx/plasma-b2c Combobox -- prop variant.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common disabled.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common readOnly.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common size l.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common size m.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common size s.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- common size xs.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- flow async items loading.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop isTargetAmount.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop listWidth, listHeight, listOverflow.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop placement.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop renderItem.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop renderValue.snap.png
  cypress/snapshots/web/components/Combobox/Combobox.component-test.tsx/plasma-web Combobox -- prop variant.snap.png
  packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
  packages/plasma-new-hope/src/components/Combobox/ComboboxNew/FloatingPopover.tsx
  packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx
Labels: plasma-components
