Repository salute-developers/plasma, pull requests merged in 2025-01, with the labels that each got.

#1698 fix: DatePicker snapshot
  cypress/snapshots/b2c/components/DatePicker/DatePicker.update-test.component-test.tsx/plasma-b2c DatePicker -- [PLASMA-T1110] DatePicker select year in popover.snap.png
  packages/plasma-b2c/src/components/DatePicker/DatePicker.update-test.component-test.tsx
Labels: changelog-skip

#1704 hotfix: reverting exports prop from package.json due to ts overcomplexity [DEV]
  packages/plasma-new-hope/package.json
  packages/sdds-cs/package.json
  packages/sdds-serv/package.json
Labels: changelog-skip

#1703 PLASMA-3978: update Slider label horizontal margin
  cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-web Slider -- _placement.snap.png
  cypress/snapshots/b2c/components/Slider/Slider.update-test.component-test.tsx/plasma-b2c Slider -- [PLASMA-T1695] Slider size=m, view=accent, pointerSize=large, pointerVisibility=hover, labelPlacement=left, scaleAlign=side, showScale, showCurrentValue, currentValueVisibility=hover, showIcon.snap.png
  cypress/snapshots/web/components/Slider/Slider.component-test.tsx/plasma-web Slider -- _placement.snap.png
  packages/plasma-b2c/src/components/Slider/Slider.config.ts
  packages/plasma-giga/src/components/Slider/Slider.config.ts
  packages/plasma-new-hope/src/components/Slider/Slider.tokens.ts
  packages/plasma-new-hope/src/components/Slider/components/Single/Single.styles.ts
  packages/plasma-new-hope/src/examples/plasma_b2c/components/Slider/Slider.config.ts
  packages/plasma-new-hope/src/examples/plasma_web/components/Slider/Slider.config.ts
  packages/plasma-web/src/components/Slider/Slider.config.ts
  packages/sdds-cs/src/components/Slider/Slider.config.ts
  packages/sdds-dfa/src/components/Slider/Slider.config.ts
  packages/sdds-finportal/src/components/Slider/Slider.config.ts
  packages/sdds-insol/src/components/Slider/Slider.config.ts
  packages/sdds-serv/src/components/Slider/Slider.config.ts
Labels: plasma-components

#1722 PLASMA-4356: make placement optional for DropdownItem [master]
  packages/plasma-new-hope/src/components/Dropdown/Dropdown.template-doc.mdx
  packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.type.ts
  website/plasma-b2c-docs/docs/components/Dropdown.mdx
  website/plasma-giga-docs/docs/components/Dropdown.mdx
  website/plasma-web-docs/docs/components/Dropdown.mdx
  website/sdds-cs-docs/docs/components/Dropdown.mdx
  website/sdds-dfa-docs/docs/components/Dropdown.mdx
  website/sdds-insol-docs/docs/components/Dropdown.mdx
  website/sdds-serv-docs/docs/components/Dropdown.mdx
Labels: Hotfix

#1723 PLASMA-4356: make placement optional for DropdownItem
  packages/plasma-new-hope/src/components/Dropdown/Dropdown.template-doc.mdx
  packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.type.ts
  website/plasma-b2c-docs/docs/components/Dropdown.mdx
  website/plasma-giga-docs/docs/components/Dropdown.mdx
  website/plasma-web-docs/docs/components/Dropdown.mdx
  website/sdds-cs-docs/docs/components/Dropdown.mdx
  website/sdds-dfa-docs/docs/components/Dropdown.mdx
  website/sdds-insol-docs/docs/components/Dropdown.mdx
  website/sdds-serv-docs/docs/components/Dropdown.mdx
Labels: changelog-skip

#1734 chore: update manually package versions
  packages/plasma-asdk/package-lock.json
  packages/plasma-asdk/package.json
  packages/plasma-b2c/package-lock.json
  packages/plasma-b2c/package.json
  packages/plasma-giga/package-lock.json
  packages/plasma-giga/package.json
  packages/plasma-new-hope/package-lock.json
  packages/plasma-new-hope/package.json
  packages/plasma-web/package-lock.json
  packages/plasma-web/package.json
  packages/sdds-cs/package-lock.json
  packages/sdds-cs/package.json
  packages/sdds-dfa/package-lock.json
  packages/sdds-dfa/package.json
  packages/sdds-finportal/package-lock.json
  packages/sdds-finportal/package.json
  packages/sdds-insol/package-lock.json
  packages/sdds-insol/package.json
  packages/sdds-serv/package-lock.json
  packages/sdds-serv/package.json
  utils/plasma-docs-ui/package.json
  website/plasma-b2c-docs/package.json
  website/plasma-giga-docs/package.json
  website/plasma-theme-builder/package.json
  website/plasma-ui-docs/package.json
  website/plasma-web-docs/package.json
  website/plasma-website/package.json
  website/sdds-cs-docs/package.json
  website/sdds-dfa-docs/package.json
  website/sdds-insol-docs/package.json
  website/sdds-serv-docs/package.json
Labels: changelog-skip
